import { ArrowLeft, Share2 } from 'lucide-react';

interface DetailPageProps {
  onNavigate: (page: string) => void;
}

export default function DetailPage({ onNavigate }: DetailPageProps) {
  const exhibit = {
    id: 10234,
    category: 'To a Lover',
    date: 'November 2024',
    reply: `Dear one,

I wonder if you still think of that night under the cherry blossoms. The way the petals fell like snow, and how we promised forever in a language we both knew was temporary.

I want you to know: it wasn't a lie. Forever exists in moments, not in years. What we felt was real, even if it couldn't last.

You didn't fail. Love doesn't work that way. Sometimes people grow in different directions, and that's not abandonment—it's honoring who you both needed to become.

The cherry blossoms fall every year, and every year they come back. Some things end not because they weren't beautiful, but because their season passed.

You can miss someone and still be glad you let them go. Both truths can live in your heart.

What you had was real. What you feel now is real too. And someday, you'll remember that night with more warmth than ache.

Until then, be gentle with yourself.

With understanding,
The Echo`
  };

  const relatedLetters = [
    { id: 1, category: 'To a Lover', preview: 'Closure doesn\'t always come from the other person...' },
    { id: 2, category: 'To Past Self', preview: 'You were brave to leave. You were brave to stay...' },
    { id: 3, category: 'To a Friend', preview: 'Growing apart doesn\'t diminish what we were...' }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-black via-gray-900 to-black pt-24 pb-16">
      <div className="max-w-4xl mx-auto px-6">
        <button
          onClick={() => onNavigate('exhibition')}
          className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors mb-8"
        >
          <ArrowLeft size={20} />
          Back to Exhibition
        </button>

        <div className="mb-8">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-4">
              <span className="text-gray-500 text-sm">Exhibit #{String(exhibit.id).padStart(5, '0')}</span>
              <span className="px-3 py-1 rounded-full text-xs border border-pink-500 text-pink-400">
                {exhibit.category}
              </span>
            </div>
            <button className="flex items-center gap-2 text-gray-400 hover:text-cyan-400 transition-colors">
              <Share2 size={18} />
              Share
            </button>
          </div>
          <p className="text-gray-500 text-sm">{exhibit.date}</p>
        </div>

        <div className="relative bg-gradient-to-br from-amber-50 to-orange-50 rounded-3xl p-12 md:p-16 shadow-2xl border-4 border-amber-100 mb-12">
          <div className="absolute top-0 left-0 w-full h-full opacity-5 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZGVmcz48cGF0dGVybiBpZD0iZ3JpZCIgd2lkdGg9IjQwIiBoZWlnaHQ9IjQwIiBwYXR0ZXJuVW5pdHM9InVzZXJTcGFjZU9uVXNlIj48cGF0aCBkPSJNIDQwIDAgTCAwIDAgMCA0MCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMDAwIiBzdHJva2Utd2lkdGg9IjEiLz48L3BhdHRlcm4+PC9kZWZzPjxyZWN0IHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JpZCkiLz48L3N2Zz4=')] rounded-3xl"></div>

          <div className="relative">
            <div className="text-amber-900 font-serif leading-relaxed whitespace-pre-line text-lg">
              {exhibit.reply}
            </div>
          </div>
        </div>

        <div className="bg-gradient-to-br from-gray-900 to-gray-800 rounded-2xl p-8 border border-gray-700 mb-12">
          <h3 className="text-white text-lg font-light mb-4">About This Letter</h3>
          <p className="text-gray-400 leading-relaxed">
            This reply was generated by AI in response to an unsent letter. The original message
            remains private and was never stored or displayed. Each letter in this exhibition
            represents a moment of emotional honesty, transformed into art through artificial intelligence.
          </p>
        </div>

        <div className="mb-8">
          <h3 className="text-white text-xl font-light mb-6">More Letters Like This</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {relatedLetters.map((letter) => (
              <button
                key={letter.id}
                onClick={() => onNavigate('detail')}
                className="bg-gradient-to-br from-gray-900 to-gray-800 rounded-xl p-4 border border-gray-700 hover:border-gray-600 transition-all text-left group"
              >
                <div className="text-xs text-gray-500 mb-2">Exhibit #{String(10000 + letter.id).padStart(5, '0')}</div>
                <div className="text-xs border border-gray-600 text-gray-400 px-2 py-1 rounded-full inline-block mb-3">
                  {letter.category}
                </div>
                <p className="text-sm text-gray-300 line-clamp-3 group-hover:text-white transition-colors">
                  {letter.preview}
                </p>
              </button>
            ))}
          </div>
        </div>

        <div className="text-center">
          <button
            onClick={() => onNavigate('write')}
            className="bg-gradient-to-r from-cyan-400 to-blue-500 text-black px-8 py-3 rounded-full font-medium hover:shadow-lg hover:shadow-cyan-500/50 transition-all"
          >
            Write Your Own Letter
          </button>
        </div>
      </div>
    </div>
  );
}
